### ISSUE TITLE
关于代码中的一些小问题

### ISSUE THREAD

**Issue by Maybewuss** [RowitZou/Lexicon-nn#1]
代码暂时还没有读完，就已读的部分有一些小问题想请教一下。

1. 在LGN中的construct_graph函数中，我发现在声明sen_nodes_mask、sen_words_length等相关变量时，会用零向量去初始化它们，然后在逐渐cat句子的字词所生成的向量，给我的感觉就像是在每句话的句首加入了一个unk字符。想知道这么做的原因是什么？
2. 在LGN中的update_graph函数以及module中定义的MultiHeadAtt中我有一些奇怪的问题。
   1. 矩阵乘法（点积， torch.mm）可以做到的事情为什么要用expand + 哈达马积（按位乘）+ sum 这种方式来做，一方面使用expand感觉会增加不必要的参数量（可能共享同一个内存地址，具体不太了解），另一方面代码中大量的 `mask[:, None, None, :, :]`这种写法，可读性有点难顶。
   2. MultiHeadAtt中为什么要使用Conv2d而不使用简单的Linear，根据在这篇论文的公式，好像这两个没什么区别。
3. 文中看您是提出了一种Recurrent-based Update Module，想了解一下作者您是怎么想出这种更新方式的。因为我觉得前面都已经摆脱RNN模型而使用图网络来构造了，那讲道理除了Aggregation采用message passing的方式来建模，Update也统一一下不是更优美一点(可能这也是message passing，只是我看的有点怪怪的，总感觉像lstm。。)，所以问题就是，您有试过其他的Update方式吗？

**Comment by RowitZou** [comment]
1. 因为具体实现时，每一个graph都加入了一条unk的边。对于一个没有边连接的孤立结点，在aggregation阶段，key和value就是unk边。unk边在aggregation阶段，key和value是所有结点。
2. 代码有些地方确实应该优化，感谢指出。对于multi-head attention的代码，我参考了我们组的工作：star-transformer的代码：https://github.com/fastnlp/fastNLP/blob/master/fastNLP/modules/encoder/star_transformer.py
3. 图网络的通用框架是message passing，包括两个部分：message calculate 和 state update，如下图（参考张岳老师ppt）：
<img width="899" alt="屏幕快照 2019-11-06 下午1 39 22" src="https://user-images.githubusercontent.com/19279727/68271313-132f0180-009b-11ea-99bf-20e1bf0e9b35.png">
我们的模型的message calculate部分就是基于Multihead Attention的aggregation模块。state update部分就是类似于GRN的更新。

**Comment by Maybewuss** [comment]
谢谢！
