### ISSUE TITLE
If you need the preprocessed data, please leave a message in this issue. (需要预处理数据请在此留言)

### ISSUE THREAD

**Issue by HwJhx** [RowitZou/Lexicon-nn#11]
您好，已经精读了您的paper，目前正在学习代码，能否提供一份预处理数据？谢谢！ 邮箱：hz_jhx@163.com

**Comment by yuxinxxhl** [comment]
@RowitZou 您好，我也在研读您的paper，同样想要预处理数据，能否给我也提供一份？谢谢！邮箱: houleiwk@foxmail.com

**Comment by Qizui** [comment]
您好，我也在研读您的paper，同样想要预处理数据，能否给我也提供一份？谢谢！邮箱: qi_zui@outlook.com
请问你们拿到了吗？能否分享一下@yuxinxxhl @HwJhx

**Comment by sibodiamond** [comment]
你好，@RowitZou，在研读你的代码，请问是否方便分享一份预处理数据，多谢！邮箱：life121612@sina.com

**Comment by HuHsinpang** [comment]
我项目里分享了一些常用的中文实体识别的预处理代码，包括onto5.0、boson、weibo等，欢迎去看看啊

**Comment by HwJhx** [comment]
OK, 感谢提醒和分享发自我的华为手机-------- 原始邮件 --------发件人： lollipop ***@***.***>日期： 2021年3月29日周一 下午3:35收件人： RowitZou/LGN ***@***.***>抄送： HwJhx ***@***.***>, Mention ***@***.***>主    题： Re: [RowitZou/LGN] 您好，已经精读了您的paper，目前正在学习代码，能否提供一份预处理数据，谢谢 (#11)

我项目里分享了一些常用的中文实体识别的预处理代码，包括onto5.0、boson、weibo等，欢迎去看看啊

**Comment by xqrshine** [comment]
@RowitZou 您好，我也在研读您的paper，预处理数据能否给我也分享一份？谢谢！邮箱:xqrshine@163.com

**Comment by happys2022** [comment]
@RowitZou 您好，我最近在研读您的论文，请问预处理数据能否分享给我一份？万分感谢！邮箱:2297064147@qq.com

**Comment by luomingli** [comment]
@RowitZou 您好，我最近在研读您的论文，请问预处理数据能否分享给我一份？万分感谢！邮箱:997452205@qq.com

**Comment by ZhangYH321** [comment]
您好，我也在研读您的paper，同样想要预处理数据，能否给我也提供一份？谢谢！邮箱: 1292154046@qq.com

**Comment by zpeng-tj** [comment]
@RowitZou 您好，我也在研读您的论文，请问预处理数据能否分享给我一份？万分感谢！邮箱:779485072@qq.com

**Comment by Coder-XIAOKAI** [comment]
您好，可以提供一份您预处理好的数据给我吗？1256422591@qq.com

**Comment by fengy-l** [comment]
您好，我最近在研读您的论文，请问预处理数据能否分享给我一份？万分感谢！邮箱：fyinga@qq.com

**Comment by ZQpengyu** [comment]
您好，我最近在研读您的论文，请问预处理数据能否分享给我一份？万分感谢！邮箱：zhaopengyuh@163.com

**Comment by littlelittleflower** [comment]
@RowitZou 您好，我也在研读您的paper，同样想要预处理数据，能否给我也提供一份？谢谢！邮箱: 1028339752@qq.com

**Comment by littlelittleflower** [comment]
请问你们拿到了吗？能否分享一下@yuxinxxhl @HwJhx 预处理数据能否给我也分享一份？谢谢！邮箱: [1028339752@qq.com](mailto:1028339752@qq.com)

**Comment by zyx214** [comment]
您好，我在研读您的paper，想要一份预处理数据，能否给我提供一份？谢谢！邮箱:979829128@qq.com

**Comment by fengy-l** [comment]
不是我的文章。。。
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "ZQpengyu"; 
Date: 2022年3月29日(星期二) 下午4:12
To: "RowitZou/LGN"; 
Cc: ***@***.***>; "Comment"; 
Subject: Re: [RowitZou/LGN] 您好，已经精读了您的paper，目前正在学习代码，能否提供一份预处理数据，谢谢 (#11)

&nbsp;


 
***@***.***

**Comment by qry0120** [comment]
您好，已经精读了您的paper，目前正在学习代码，能否提供一份预处理数据？谢谢！ 邮箱：qiruiyan@163.com

**Comment by qry0120** [comment]
您好，已经精读了您的paper，目前正在学习代码，能否提供一份预处理数据？谢谢！ 邮箱：qiruiyan2021@163.com

**Comment by qry0120** [comment]
@RowitZou 您好，我也在研读您的paper，同样想要预处理数据，能否给我也提供一份？谢谢！邮箱:qiruiyan2021@163.com

**Comment by qry0120** [comment]
@RowitZou 您好，我也在研读您的paper，同样想要预处理数据，能否给我也提供一份？谢谢！邮箱:[qiruiyan2021@163.com]

**Comment by WhoopsLeo** [comment]
@RowitZou 您好，我在研读您的paper，想要预处理数据，能否给我也提供一份？谢谢！麻烦了！ 邮箱：leoxuwj@163.com

**Comment by jennierubyjanee** [comment]
您好，已经精读了您的paper，目前正在学习代码，能否提供一份预处理数据？谢谢！ 邮箱：1181384708@qq.com

**Comment by HongzhiQ** [comment]
您好，已经精读了您的paper，目前正在学习代码，能否提供一份预处理数据？谢谢！ 邮箱：qhz123@emails.bjut.edu.cn

**Comment by SanJat-Lau** [comment]
您好，已经精读了您的paper，目前正在学习代码，能否提供一份预处理数据？谢谢！ 邮箱：[137638941@qq.com](mailto:137638941@qq.com)

**Comment by Astronaut323** [comment]
您好，请问可以发我一份预处理后的数据吗？谢谢！ 邮箱：1033538647@qq.com

**Comment by JustinPeanut** [comment]
您好，已经精读了您的paper，目前正在学习代码，能否提供一份预处理数据？谢谢！ 邮箱：jutinpeanut@gmail.com

**Comment by bugless01** [comment]
您好，我最近在研读您的论文，请问预处理数据能否分享给我一份？万分感谢！邮箱：1358522714@qq.com

**Comment by QianGuYiDi** [comment]
您好，我也在研读您的论文，同样想要预处理数据，能否给我也提供一份？谢谢！邮箱：gjw71023@126.com
