### ISSUE TITLE
Want to know estimate for wall time of LGN

### ISSUE THREAD

**Issue by Jivnesh** [RowitZou/Lexicon-nn#12]
I was trying to use this model for another sequence tagging problem. I have around 93k training samples in my test set. Its taking 4-5 hours for one epoch. I wanted to know how is the training time for models trained on Chinese data? Any estimation? Is it possible to improve training speed?

**Comment by RowitZou** [comment]
The training time of Resume (about 124k samples) is within 1 hour for each epoch. 

The process of graph construction consumes much time. A longer text sequence or a denser sentence graph would take more time. If possible, splitting long sequences into pieces may help improve training speed. A larger batch size also works.

**Comment by Jivnesh** [comment]
@RowitZou Thanks for the quick reply. I have a few more queries. Can you please help me to get a better understanding?
(1) For the resume dataset, is it that the model is getting trained for 100 epochs? Does that mean approximately 100 hours of training time?
(2) Is early stopping is there if the model gets saturated?
(3) What will be the impact on accuracy if I increase the batch size?
(4) How large batch size can be kept?

**Comment by RowitZou** [comment]
(1)(2) Early stopping works. If the performance on the dev set gets stable, the subsequent training epochs are not necessary. And the training procedure generally does not require 100 epochs. 
(3) For large datasets, it only has an influence on the convergence speed and barely changes the accuracy. For small datasets, the batch size might have a certain impact on accuracy. 
(4) It depends on the GPU memory size. Empirically, we set the batch size to a value that maximizes the utilization of GPU memory.

**Comment by Jivnesh** [comment]
I was trying with default parameter settings. I found that the default batch size is 1. May I know what is batch size parameter for the Resume dataset? My GPU memory size is 11GB.

**Comment by RowitZou** [comment]
Resume and Weibo are both small datasets. The batch size is 1 because we found a small batch size is suitable for small datasets. The batch size for OntoNotes is 4, which is applicable to an 11GB GPU.

**Comment by Jivnesh** [comment]
Extremely grateful for your timely responses. Thank you very much. I am able to train it with a batch size of 16. Now training speed is quite good!
