### ISSUE TITLE
关于全局中继节点（global relay node)

### ISSUE THREAD

**Issue by JackySnake** [RowitZou/Lexicon-nn#2]
您好，您的工作非常吸引我，我在精读您的论文，关于全局的中继节点我有些不理解，想请教一下您。
1.在构建图的部分，全局中继节点是连接了所有的节点和边，连接节点我能理解，就是建立起任意两个字符之前的二跳连接（two-step),但是连接边是怎么链接的呢？是指这个节点链接了（Figure 2中的）“c1-e1,2-c2"中的e1,2节点当作边的描述吗？但是我从原文看，好像e1,2只是一个边，而不是节点。
2.在构建图的部分，the transpose of the constructed graph是把整个构建好的图再从连接方向上做了转置对吗？
期待您的解答，感谢！

**Comment by RowitZou** [comment]
1. 具体实现时，结点和边都表示为向量，中继结点也是向量。连接的概念，本质上是中继结点的向量，融合图中所有元素（包括结点和边）的向量信息。论文中的**结点**、**边**、**连接**三个概念是独立的，本质上结点代表字(char)，边代表词(word)，为了符合Graph的表述和一般人的理解习惯，论文中将字和词描述为结点和边。具体地，结点与边连接，结点与结点不直接连接，结点与中继结点连接、边与中继结点连接、各个元素(结点和边)通过中继结点形成二跳连接。
2. 参考1中描述，transpose是在构建好的图上，把**边**的方向做了转置。

**Comment by JackySnake** [comment]
我大约明白了，就是在论文中，其实很明确字符是节点（node），而文中的边（edge）其实代表的是词，在具体的实现中也是当做节点来考虑的，由向量表示，这样就组成了图的特征矩阵，而图的邻接矩阵也是如此构造的,我的理解是否正确？

**Comment by RowitZou** [comment]
是的。具体实现中，除了中继结点，邻接矩阵的size是：结点数 * 边数，因为结点与结点不直接连接，边与边不直接连接。

**Comment by JackySnake** [comment]
不好意思，再向您请教一下，如果这样的话，邻接矩阵是不是就不是对称的方阵了？那么对图神经网络来说，是不是前面拉普拉斯矩阵那里要有些变化？可能是因为我只是了解一些图卷积网络而产生的疑问，如果误解还请您多多谅解。

**Comment by RowitZou** [comment]
拉普拉斯矩阵是GCN用到的，用于卷积。这篇论文是基于GNN通用的 massege passing 框架。具体可看一个已关闭的 [issue](https://github.com/RowitZou/LGN/issues/1)。

**Comment by JackySnake** [comment]
好的，非常感谢您的回复！
