### ISSUE TITLE
关于复现Weibo数据集结果的问题

### ISSUE THREAD

**Issue by GabrielThompson** [RowitZou/Lexicon-nn#5]
您好，我用的是
https://github.com/hltcoe/golden-horse
该项目里面提供的Weibo数据集（weiboNER.conll.dev、weiboNER.conll.test、weiboNER.conll.train）但是用你提供的训练好的model_weibo_best模型在decoding模式下生成测试集的预测文件时会报错：
File "/media/gabriel/LGN-master/model/LGN.py", line 35, in __init__
    self.char_embedding.weight.data.copy_(torch.from_numpy(data.pretrain_char_embedding))
RuntimeError: The expanded size of the tensor (3357) must match the existing size (3358) at non-singleton dimension 0
可能是处理数据集的时候编码格式问题引起的word字典大小差异，如果可以的话能麻烦你发一份Weibo数据集到我的邮箱吗？

**Comment by RowitZou** [comment]
你好，预处理的数据集已发送邮箱。

**Comment by SeekPoint** [comment]
同样需要preprocessed datasets， ykpaper@126.com

**Comment by Maybewuss** [comment]
@RowitZou 
作者你好，我也遇到了一样的问题，可以也发一份处理完的数据集给我吗？
邮箱是834733550@qq.com

**Comment by zhangyimi** [comment]
您好，同样需要预处理数据集。 369217411@qq.com
