### ISSUE TITLE
关于cudnn，cuda版本问题

### ISSUE THREAD

**Issue by samaritanhu** [RowitZou/Lexicon-nn#6]
系统 Ubuntu18.04
Cuda 10.0
cuDNN 7.6.4
Pytorch 1.14.0
会报错：RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

虚拟环境版本
Cuda: 9.0
cuDNN 7.6.4 for cuda9.0
Pytorch 0.4.1
会报错：RuntimeError: cuDNN error: CUDNN_STATUS_SUCCESS

具体问一下代码执行的环境和版本应该是怎么样吖~

**Comment by samaritanhu** [comment]
GPU是NVIDIA GeForce RTX 2060 super

**Comment by RowitZou** [comment]
我当时的环境是：
Cuda 9.0， cuDNN 7，pytorch 0.4.1/1.0.0，GPU：Titan Xp/1080Ti

https://discuss.pytorch.org/t/runtimeerror-cudnn-error-cudnn-status-success/28045
参考上述连接，试试将虚拟环境版本的cuda9.0升级到cuda9.2？

**Comment by samaritanhu** [comment]
Thanks!!!!

**Comment by Jivnesh** [comment]
### Error: RuntimeError: cuDNN error: CUDNN_STATUS_SUCCESS
I too got this error with Cuda 9.0. It got resolved when I switched to Cuda 9.2
